#!/bin/sh

BAT=$(acpi -b | grep -E -o '[0-9][0-9]?[0-9]?%')

if acpi -b | grep -q "Charging"; then
	echo "<span size=\"large\">󰂄</span> $BAT"
	exit 0
elif [ ${BAT%?} -le 30 ]; then
	icon="󰁼"
elif [ ${BAT%?} -le 60 ]; then
	icon="󰁾"
elif [ ${BAT%?} -le 90 ]; then
	icon="󰂀"
else
	icon="󰁹"
fi

echo "<span size=\"large\">$icon</span> $BAT"

[[ ${BAT%?} -le 15 ]] && exit 33 || exit 0
