#!/bin/sh

output=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | cut -b 9,11-)
VOL=$((10#$(echo "$output" | cut -b -3)))

if [[ $output == *"[MUTED]" ]]; then
	icon="󰝟"
	#echo "<span size=\"large\">󰝟</span> 0%"
elif [[ $VOL -eq 0 ]]; then
	icon="󰝟"
elif [[ $VOL -le 25 ]]; then
	icon="󰕿"
elif [[ $VOL -le 65 ]]; then
	icon="󰖀"
else
	icon="󰕾"
fi

echo "<span size=\"large\">$icon</span> $VOL%"
[[ $output == *"[MUTED]" ]] && exit 33 || exit 0
